spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_5f9db8904cf9616?reconnect=true
    username: b7058579bffd68
    password: a6d08053
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: warn
    com.jason: info
  file:
    name: log/blog-pro.log

server:
  port: 8081